"""Owner Hot-Queue Day Action Pack — daily build of CSV+MD for the owner + ntfy push.

Goal: turn the 42 (or however many) `calling_flagged` / hot-reply cards in
`/api/ops/hotqueue` into a single click-ready file the owner can blast from
their phone in 10 minutes.

Outputs:
  data/hot_queue_for_owner_<YYYY-MM-DD>.csv — Excel-friendly, WA link column
  data/hot_queue_for_owner_<YYYY-MM-DD>.md  — top-15 with clickable wa.me links
  ntfy push → owner phone topic `leadgen-d6b984bd`
Idempotent: re-running on same day overwrites the file. Reads token from
`NTFY_TOKEN` env (matches what app/notifier.py uses). Never raises — wraps in
broad except so the scheduler mark stays ok even if ntfy down.
"""
from __future__ import annotations

import csv
import os
import urllib.request
from datetime import datetime, timezone

from app.marketing.upi_kit import payment_kit
from app.platform import reply_agent


async def build_owner_pack(limit: int = 200, push_ntfy: bool = True) -> dict:
    """Build today's owner action pack + optional ntfy push. Never raises."""
    try:
        rows = reply_agent.hot_queue(limit=limit, scope="boss") or []
    except Exception as exc:  # never raise — defensive surface
        return {"ok": False, "error": f"hot_queue_unavailable: {exc}", "rows": 0}

    # Inject fallback UPI Payment Flows if card doesn't already have wa_link
    for x in rows:
        if not x.get("wa_link") and x.get("phone"):
            raw_phone = str(x.get("phone") or "").strip().lstrip("+")
            if raw_phone.startswith("91") and len(raw_phone) == 12:
                clean_phone = raw_phone
            elif len(raw_phone) == 10:
                clean_phone = f"91{raw_phone}"
            else:
                clean_phone = raw_phone
            vpa = x.get("vpa", "default.upi@bank")
            amount = x.get("amount", 499)
            kit = payment_kit(x.get("business_name", "Lead"), vpa, amount, "LeadGen Payment")
            from urllib.parse import quote
            x["wa_link"] = f"https://wa.me/{clean_phone}?text={quote(kit['wa_payment_msg'])}"
            if not x.get("draft"):
                x["draft"] = kit["wa_payment_msg"]

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    csv_path = f"data/hot_queue_for_owner_{today}.csv"
    md_path = f"data/hot_queue_for_owner_{today}.md"

    try:
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f)
            w.writerow(
                [
                    "rank",
                    "business",
                    "from",
                    "niche",
                    "city",
                    "channel",
                    "intent",
                    "phone",
                    "wa_link",
                    "draft_preview",
                ]
            )
            for i, x in enumerate(rows, 1):
                wa = x.get("wa_link", "") or ""
                phone = wa.split("wa.me/")[1].split("?")[0] if "wa.me/" in wa else ""
                w.writerow(
                    [
                        i,
                        (x.get("business_name") or "")[:40],
                        (x.get("from") or "")[:40],
                        x.get("niche", ""),
                        x.get("city", ""),
                        x.get("channel", ""),
                        x.get("intent", ""),
                        phone,
                        wa,
                        (x.get("draft") or "").replace("\r", " ").replace("\n", " ").strip()[:120],
                    ]
                )
    except Exception as exc:
        return {"ok": False, "error": f"csv_write_failed: {exc}", "rows": 0}

    try:
        with open(md_path, "w", encoding="utf-8") as f:
            f.write(f"# Owner Hot-Queue Day Action Pack — {today}\n\n")
            f.write(
                f"**Total hot leads:** {len(rows)} | "
                f"**All have WA link + UPI deep-link pre-embedded**\n\n"
            )
            f.write("## Top 15 (action these first)\n\n")
            for i, x in enumerate(rows[:15], 1):
                wa = x.get("wa_link", "") or ""
                phone = wa.split("wa.me/")[1].split("?")[0] if "wa.me/" in wa else "?"
                f.write(f"### {i}. {x.get('business_name', '?')}\n")
                f.write(f"- **Phone:** `{phone}`\n")
                f.write(f"- **Niche:** {x.get('niche', '?')}\n")
                f.write(f"- **City:** {x.get('city', '?')}\n")
                f.write(f"- **WA link:** <{wa}>\n")
                f.write(
                    f"- **Draft preview:** "
                    f"{(x.get('draft') or '')[:140]}\n\n"
                )
            f.write(
                f"\n---*\n*Generated by Hermes Owner OS. "
                f"Full CSV: `data/hot_queue_for_owner_{today}.csv`*\\n"
            )
    except Exception:
        pass  # md is nice-to-have

    ntfy_status = "skipped"
    if push_ntfy and rows:
        ntfy_status = await _push_ntfy(rows, today)

    return {
        "ok": True,
        "rows": len(rows),
        "csv": csv_path,
        "md": md_path,
        "ntfy": ntfy_status,
    }


async def _push_ntfy(rows: list, today: str) -> str:
    """Best-effort ntfy push to owner topic. ASCII-safe (no emoji header)."""
    try:
        token = os.environ.get("NTFY_TOKEN", "").strip()
        topic = os.environ.get(
            "NTFY_TOPIC", os.environ.get("NTFY_DEFAULT_TOPIC", "leadgen-d6b984bd")
        ).strip() or "leadgen-d6b984bd"
        base = os.environ.get("NTFY_URL", "http://ntfy:80").strip()
        if not base or not topic:
            return "skip_no_config"
        url = f"{base.rstrip('/')}/{topic}"
        top3 = rows[:3]
        lines = [
            f"Hot Queue Day Pack ready — {len(rows)} leads",
            "",
        ]
        for x in top3:
            wa = x.get("wa_link", "") or ""
            ph = wa.split("wa.me/")[1].split("?")[0] if "wa.me/" in wa else "?"
            lines.append(
                f"- {str(x.get('business_name', '?'))[:30]} "
                f"({x.get('city', '?')}) -> wa.me/{ph}"
            )
        lines += [
            "",
            f"Full: data/hot_queue_for_owner_{today}.md",
            f"CSV: data/hot_queue_for_owner_{today}.csv",
        ]
        body = "\n".join(lines).encode("ascii", "replace")
        headers = {
            "Title": f"{len(rows)} hot leads ready".encode("ascii", "replace"),
            "Priority": "high",
            "Tags": "fire,zap",
        }
        if token:
            headers["Authorization"] = f"Bearer {token}"
        req = urllib.request.Request(
            url, data=body, headers=headers, method="POST"
        )
        with urllib.request.urlopen(req, timeout=5) as r:
            return f"sent_{r.status}"
    except Exception as exc:
        return f"failed: {str(exc)[:120]}"


__all__ = ["build_owner_pack"]
