"""Niche catalog data — the builtin NICHES dict (per-niche tier / bands / copy / config).

Extracted from app/niches.py (2026-06-20 refactor) to separate ~958 lines of pure
catalog data from the logic helpers. Re-exported by niches.py so
`from app.niches import NICHES` keeps working everywhere (billing, voice, data API).
"""

NICHES = {
    # ====================================================================== #
    # S-TIER — flagship niches: sell these first
    # ====================================================================== #
    "ai_marketing": {
        "name": "AI Marketing Services",
        "tier": "S",
        "category": "marketing",
        "content_focus": ["festival posters", "GBP optimization", "social posts", "reels"],
        "target_type": "b2b",
        "b2b_client": "local businesses needing marketing",
        "end_customer": "business owners",
        "keywords": [
            "local business marketing",
            "ai marketing services",
            "digital marketing for small business",
            "google business profile optimization",
        ],
        "avg_deal_value": "₹36,000–1,44,000/yr",
        "avg_ticket_inr": "₹3–12K/mo subscription (₹36K–1.44L/yr LTV)",
        "pitch_hook": "posts, Google ranking, festival posters — plus an AI that calls every inquiry in 2 minutes; no Indian competitor bundles both",
        "lead_band": "A",  # voice-product band (ADR-009; old per-lead mid ₹650)
        "qualification_questions": [
            "Abhi aap apni marketing kaise karte ho — khud, staff, ya agency?",
            "Google pe aapka business search karne par dikhta hai kya?",
            "Website ya Google se aayi inquiries ka follow-up kaun karta hai?",
        ],
    },
    "studying_abroad": {
        "name": "Study Abroad Consultants",
        "tier": "S",
        "category": "leadgen",
        "content_focus": ["offer posts", "lead forms"],
        "target_type": "b2c",
        "b2b_client": "Overseas education consultancies",
        "end_customer": "Students/parents (country, budget, intake qualification + counseling booking)",
        "keywords": [
            "study abroad consultants",
            "overseas education counsellors",
            "visa consultants",
        ],
        "avg_deal_value": "₹2,00,000+",
        "avg_ticket_inr": "₹2–3L commission/enrolled student (10–15% of first-year tuition)",
        "pitch_hook": "every inquiry counselled within minutes — enrollments worth ₹2-3L commission each",
        "lead_band": "B",  # voice-product band (ADR-009; old per-lead mid ₹1750)
        "qualification_questions": [
            "Do you handle admissions for USA/UK/Canada?",
            "Are you looking for students with budget above 20L?",
            "Do you have university tie-ups?",
        ],
    },
    "home_loans": {
        "name": "Home Loans & LAP (DSA)",
        "tier": "S",
        "category": "leadgen",
        "content_focus": ["offer posts", "lead forms"],
        "target_type": "b2c",
        "b2b_client": "Loan DSAs, mortgage brokers, fintech lending partners",
        "end_customer": "Home-loan seekers (eligibility, ticket size, balance-transfer qualification)",
        "keywords": [
            "home loan dsa",
            "loan agents",
            "mortgage brokers india",
            "loan against property agents",
        ],
        "avg_deal_value": "₹25,00,000+",
        "avg_ticket_inr": "₹23–33L avg ticket (DSA payout 0.5–1.5%)",
        "pitch_hook": "your telecalling team replaced — eligibility-checked, doc-ready borrowers on your calendar",
        "lead_band": "B",  # voice-product band (ADR-009; old per-lead mid ₹1000)
        "qualification_questions": [
            "Are you an active DSA with bank/NBFC tie-ups?",
            "What loan ticket sizes do you focus on?",
            "How many files do you log per month?",
        ],
    },
    "solar_residential": {
        "name": "Residential Rooftop Solar",
        "tier": "S",
        "category": "both",
        "content_focus": ["subsidy posts", "before-after reels", "offer posters"],
        "target_type": "b2c",
        "b2b_client": "Solar installers & EPC dealers (residential)",
        "end_customer": "Homeowners (roof ownership, bill size, subsidy interest → site-survey booking)",
        "keywords": [
            "solar installers residential",
            "rooftop solar dealers",
            "solar panel installation company",
        ],
        "avg_deal_value": "₹1,50,000+",
        "avg_ticket_inr": "₹1.5–1.8L per 3kW install (PM Surya Ghar demand)",
        "pitch_hook": "subsidy-curious homeowners qualified for roof & bill size before your surveyor leaves the office",
        "lead_band": "A",  # voice-product band (ADR-009; old per-lead mid ₹700)
        "qualification_questions": [
            "Do you install residential rooftop systems?",
            "Which cities/areas do you cover?",
            "How many site surveys can your team handle weekly?",
        ],
    },
    "solar_commercial": {
        "name": "Commercial Solar Installers",
        "tier": "S",
        "category": "leadgen",
        "content_focus": ["offer posts", "lead forms"],
        "target_type": "b2b",
        "b2b_client": "Solar EPC companies (C&I segment)",
        "end_customer": "Factory/warehouse owners (roof suitability, load, capex appetite)",
        "keywords": [
            "commercial solar installers",
            "solar epc companies",
            "industrial solar solutions",
        ],
        "avg_deal_value": "₹20,00,000+",
        "avg_ticket_inr": "₹20L+ per C&I project",
        "pitch_hook": "qualify factory owners for roof suitability before you visit",
        "lead_band": "C",  # voice-product band (ADR-009; old per-lead mid ₹2250)
        "qualification_questions": [
            "Do you handle commercial installations above 100kW?",
            "Are you looking for industrial leads?",
            "What is your installation capacity per month?",
        ],
    },
    "insurance": {
        "name": "Health & Term Insurance",
        "tier": "S",
        "category": "leadgen",
        "content_focus": ["offer posts", "lead forms"],
        "target_type": "b2c",
        "b2b_client": "Insurance agencies, POSPs, broker teams",
        "end_customer": "Families/professionals (age, cover need, premium budget) — IRDAI/DND compliant",
        "keywords": [
            "insurance agents",
            "health insurance brokers",
            "term insurance advisors",
            "posp insurance",
        ],
        "avg_deal_value": "₹25,000+",
        "avg_ticket_inr": "₹15–50K premium (35–40% first-year commission)",
        "pitch_hook": "renewal reminders + new-policy qualification on autopilot — the classic telesales niche without telecaller churn",
        "lead_band": "A",  # voice-product band (ADR-009; old per-lead mid ₹550)
        "qualification_questions": [
            "Are you an IRDAI-registered agent/broker/POSP?",
            "Which products do you focus on — health, term, motor?",
            "Do you have a renewal book to re-engage?",
        ],
    },
    "coaching": {
        "name": "Coaching Institutes (NEET/JEE/UPSC)",
        "tier": "S",
        "category": "both",
        "content_focus": ["result posters", "admission posts", "reels", "reviews"],
        "target_type": "b2c",
        "b2b_client": "Test-prep coaching institutes",
        "end_customer": "Parents/students (target exam, class, budget → counseling session booking)",
        "keywords": [
            "neet coaching institutes",
            "jee coaching centers",
            "upsc coaching",
            "test prep institutes",
        ],
        "avg_deal_value": "₹1,50,000+",
        "avg_ticket_inr": "₹1.5–2.5L/year fees (₹58,000Cr industry)",
        "pitch_hook": "every admission inquiry counselled the same hour — seats filled before parents compare brochures",
        "lead_band": "A",  # voice-product band (ADR-009; old per-lead mid ₹850)
        "qualification_questions": [
            "Which exams do you coach for?",
            "What is your annual fee structure?",
            "Do you have admission counselors following up on inquiries today?",
        ],
    },
    # ====================================================================== #
    # A-TIER — strong economics, proven phone funnels
    # ====================================================================== #
    "interior_designers": {
        "name": "Interior Design Studios",
        "tier": "A",
        "category": "marketing",
        "content_focus": ["portfolio reels", "before-after posts", "festival posters"],
        "target_type": "b2c",
        "b2b_client": "Interior design firms & studios",
        "end_customer": "Homeowners (BHK, budget band, possession date → design-consult booking)",
        "keywords": ["interior designers", "home interior companies", "turnkey interior firms"],
        "avg_deal_value": "₹10,00,000+",
        "avg_ticket_inr": "₹4–20L per 2BHK project",
        "pitch_hook": "possession-ready homeowners qualified by budget before your designer picks up the phone",
        "lead_band": "B",  # voice-product band (ADR-009; old per-lead mid ₹1750)
        "qualification_questions": [
            "Do you handle turnkey residential projects?",
            "What is your minimum project budget?",
            "Which cities do you operate in?",
        ],
    },
    "modular_kitchen": {
        "name": "Modular Kitchen Manufacturers",
        "tier": "A",
        "category": "both",
        "content_focus": ["catalog posters", "before-after reels", "offers"],
        "target_type": "b2c",
        "b2b_client": "Modular kitchen brands & showrooms",
        "end_customer": "Homeowners (kitchen size, budget, timeline → showroom/site visit)",
        "keywords": [
            "modular kitchen manufacturers",
            "luxury kitchen showrooms",
            "italian kitchen dealers",
        ],
        "avg_deal_value": "₹2,00,000+",
        "avg_ticket_inr": "₹1.2–6.5L per kitchen",
        "pitch_hook": "showroom visits from budget-qualified homeowners, not window shoppers",
        "lead_band": "B",  # voice-product band (ADR-009; old per-lead mid ₹1050)
        "qualification_questions": [
            "Do you manufacture in-house or trade?",
            "Are you looking for direct homeowner leads?",
            "Do you deal in premium German/Italian fittings?",
        ],
    },
    "dental_implants": {
        "name": "Dental Clinics (Implants/Aligners)",
        "tier": "A",
        "category": "both",
        "content_focus": ["before-after posts", "health-day posts", "reviews", "GBP optimization"],
        "target_type": "b2c",
        "b2b_client": "Dental clinics & chains",
        "end_customer": "Patients (treatment need, budget → appointment booking + reminders)",
        "keywords": ["dental implant clinics", "cosmetic dentistry", "premium dental clinic"],
        "avg_deal_value": "₹50,000+",
        "avg_ticket_inr": "₹20–50K/tooth, full-mouth ₹3–8L",
        "pitch_hook": "fill your empty chair slots with high-value implant patients",
        "lead_band": "B",  # voice-product band (ADR-009; old per-lead mid ₹1000)
        "qualification_questions": [
            "Do you offer dental implants?",
            "Are you looking to increase high-ticket patient footfall?",
            "Do you have a dedicated sales team for follow-ups?",
        ],
    },
    "hair_transplant": {
        "name": "Hair Transplant Clinics",
        "tier": "A",
        "category": "both",
        "content_focus": ["before-after reels", "reviews", "offer posts"],
        "target_type": "b2c",
        "b2b_client": "Hair transplant & aesthetics clinics",
        "end_customer": "Prospects (grade, budget, city → consult booking; market CPQL ~₹4,100)",
        "keywords": ["hair transplant clinics", "hair restoration centers", "aesthetics clinics"],
        "avg_deal_value": "₹1,50,000+",
        "avg_ticket_inr": "₹1–3.5L per procedure",
        "pitch_hook": "consults booked at half the ₹4,000+ cost-per-qualified-lead you pay ads today",
        "lead_band": "C",  # voice-product band (ADR-009; old per-lead mid ₹1850)
        "qualification_questions": [
            "How many consults does your counselor team handle daily?",
            "What is your average procedure value?",
            "Are you running Google/Meta ads currently?",
        ],
    },
    "ivf_clinics": {
        "name": "IVF & Fertility Clinics",
        "tier": "A",
        "category": "leadgen",
        "content_focus": ["offer posts", "lead forms"],
        "target_type": "b2c",
        "b2b_client": "IVF & fertility centers",
        "end_customer": "Couples (empathetic intake, history, budget → doctor consult booking)",
        "keywords": ["ivf centers", "fertility clinics", "ivf hospitals"],
        "avg_deal_value": "₹1,50,000+",
        "avg_ticket_inr": "₹1–2.5L per cycle",
        "pitch_hook": "compassionate 24/7 intake — every inquiry answered, qualified and booked with a counselor",
        "lead_band": "C",  # voice-product band (ADR-009; old per-lead mid ₹1500)
        "qualification_questions": [
            "How many new patient inquiries do you get monthly?",
            "Do you have counselors for first-call intake?",
            "Which cities are your centers in?",
        ],
    },
    "immigration": {
        "name": "Immigration & PR Consultants",
        "tier": "A",
        "category": "leadgen",
        "content_focus": ["offer posts", "lead forms"],
        "target_type": "b2c",
        "b2b_client": "Immigration/PR consultancies",
        "end_customer": "Aspirants (eligibility points-check, country, budget → consult booking)",
        "keywords": ["immigration consultants", "canada pr consultants", "visa services australia"],
        "avg_deal_value": "₹75,000+",
        "avg_ticket_inr": "₹50K–1.25L per case",
        "pitch_hook": "eligibility-scored PR aspirants on your counselors' calendars every morning",
        "lead_band": "C",  # voice-product band (ADR-009; old per-lead mid ₹1400)
        "qualification_questions": [
            "Which countries do you process — Canada, Australia, UK?",
            "Are you ICCRC/MARA registered or partnered?",
            "How many cases do you file monthly?",
        ],
    },
    "upskilling": {
        "name": "Upskilling & EdTech Programs",
        "tier": "A",
        "category": "leadgen",
        "content_focus": ["offer posts", "lead forms"],
        "target_type": "b2c",
        "b2b_client": "EdTech companies, certification institutes",
        "end_customer": "Working professionals (career goal, budget, EMI eligibility → counselor call)",
        "keywords": [
            "edtech companies",
            "professional certification institutes",
            "online course providers",
        ],
        "avg_deal_value": "₹1,00,000+",
        "avg_ticket_inr": "₹50K–3L per program",
        "pitch_hook": "the BYJU's-style telecalling engine — without the 200-person telecalling floor",
        "lead_band": "A",  # voice-product band (ADR-009; old per-lead mid ₹550)
        "qualification_questions": [
            "What programs do you sell and at what ticket size?",
            "Do you have an inside-sales team today?",
            "What is your current cost per enrollment?",
        ],
    },
    "recruitment": {
        "name": "Recruitment & Staffing Agencies",
        "tier": "A",
        "category": "leadgen",
        "content_focus": ["offer posts", "lead forms"],
        "target_type": "both",
        "b2b_client": "Recruitment/staffing firms",
        "end_customer": "Candidates (screening at scale) + employer mandates (BD calls)",
        "keywords": [
            "recruitment agencies",
            "staffing companies",
            "it recruitment agencies",
            "headhunters",
        ],
        "avg_deal_value": "₹1,00,000+",
        "avg_ticket_inr": "8.33–16.67% of CTC ≈ ₹50K–2L per placement",
        "pitch_hook": "screen 200 candidates a day and qualify new employer mandates — one agent, both sides",
        "lead_band": "A",  # voice-product band (ADR-009; old per-lead mid ₹550)
        "qualification_questions": [
            "Do you do permanent hiring, staffing, or both?",
            "How many open mandates are you working?",
            "What volumes of candidate screening do you do weekly?",
        ],
    },
    # ====================================================================== #
    # B-TIER — solid volume/strategic plays
    # ====================================================================== #
    "hvac_commercial": {
        "name": "Commercial HVAC",
        "tier": "B",
        "category": "leadgen",
        "content_focus": ["offer posts", "lead forms"],
        "target_type": "b2b",
        "b2b_client": "HVAC contractors & AMC providers",
        "end_customer": "IT parks, malls, offices (AMC renewals, retrofit projects)",
        "keywords": [
            "hvac contractors commercial",
            "central ac installation",
            "industrial cooling solutions",
        ],
        "avg_deal_value": "₹5,00,000+",
        "avg_ticket_inr": "₹5L+ projects; AMC recurring",
        "pitch_hook": "secure high-value AMC contracts with IT parks",
        "lead_band": "C",  # voice-product band (ADR-009; old per-lead mid ₹2250)
        "qualification_questions": [
            "Do you take AMC contracts for IT parks/malls?",
            "What is your minimum project size?",
            "Are you looking for more B2B contracts?",
        ],
    },
    "b2b_suppliers": {
        "name": "Manufacturing & B2B Suppliers",
        "tier": "B",
        "category": "leadgen",
        "content_focus": ["offer posts", "lead forms"],
        "target_type": "b2b",
        "b2b_client": "Manufacturers/wholesalers on IndiaMART/TradeIndia",
        "end_customer": "Business buyers (RFQ follow-up in minutes — speed wins the order)",
        "keywords": ["manufacturers india", "industrial suppliers", "wholesale suppliers b2b"],
        "avg_deal_value": "₹2,00,000+",
        "avg_ticket_inr": "₹50K–50L orders (IndiaMART BuyLead ₹16–24 raw)",
        "pitch_hook": "every IndiaMART RFQ called back in 5 minutes — before the other 6 suppliers wake up",
        "lead_band": "A",  # voice-product band (ADR-009; old per-lead mid ₹275)
        "qualification_questions": [
            "Are you buying BuyLeads on IndiaMART today?",
            "What is your average order value?",
            "Who follows up your RFQs currently?",
        ],
    },
    "travel_packages": {
        "name": "International Travel Packages",
        "tier": "B",
        "category": "both",
        "content_focus": ["package posters", "destination reels", "offers"],
        "target_type": "b2c",
        "b2b_client": "Travel agencies & tour operators",
        "end_customer": "Families/couples (destination, dates, budget → itinerary consult)",
        "keywords": [
            "travel agencies international packages",
            "tour operators",
            "holiday package companies",
        ],
        "avg_deal_value": "₹3,00,000+",
        "avg_ticket_inr": "₹2.9–3.2L per international trip (couple)",
        "pitch_hook": "itinerary-ready travellers with dates and budgets locked — not brochure collectors",
        "lead_band": "A",  # voice-product band (ADR-009; old per-lead mid ₹700)
        "qualification_questions": [
            "Which destinations do you specialize in?",
            "What is your average package value?",
            "Do you handle visas in-house?",
        ],
    },
    "packers_movers": {
        "name": "Packers & Movers",
        "tier": "B",
        "category": "leadgen",
        "content_focus": ["offer posts", "lead forms"],
        "target_type": "b2c",
        "b2b_client": "Relocation companies",
        "end_customer": "Households/offices (move date, inventory size → instant quote callback)",
        "keywords": ["packers and movers", "relocation services", "household shifting services"],
        "avg_deal_value": "₹30,000+",
        "avg_ticket_inr": "₹11–55K intercity moves",
        "pitch_hook": "fastest quote wins the move — your agent calls back in 60 seconds, day or night",
        "lead_band": "A",  # voice-product band (ADR-009; old per-lead mid ₹350)
        "qualification_questions": [
            "Which routes/cities do you cover?",
            "How many moves do you handle monthly?",
            "Who answers your inquiry calls after hours?",
        ],
    },
    "hotels_mice": {
        "name": "Hotels & Banquets (Corporate/MICE)",
        "tier": "B",
        "category": "leadgen",
        "content_focus": ["offer posts", "lead forms"],
        "target_type": "b2b",
        "b2b_client": "Hotels, resorts, convention centers",
        "end_customer": "Corporate event planners, HR/admin teams (event size, dates, budget)",
        "keywords": [
            "hotels corporate events",
            "convention centers",
            "mice venues",
            "conference halls",
        ],
        "avg_deal_value": "₹5,00,000+",
        "avg_ticket_inr": "MICE market $37.75B; corporate events high-value",
        "pitch_hook": "banquet inquiries qualified for date, size and budget — sales team only talks to real events",
        "lead_band": "B",  # voice-product band (ADR-009; old per-lead mid ₹1750)
        "qualification_questions": [
            "What is your banquet/hall capacity?",
            "Do you target corporate MICE business?",
            "Who handles inbound event inquiries today?",
        ],
    },
    "digital_marketing": {
        "name": "Digital Marketing Agencies",
        "tier": "B",
        "category": "leadgen",
        "content_focus": ["offer posts", "lead forms"],
        "target_type": "b2b",
        "b2b_client": "Agencies (also white-label channel partners for our platform)",
        "end_customer": "SMB owners needing marketing (audit-call booking)",
        "keywords": ["digital marketing agency", "seo company", "social media marketing agency"],
        "avg_deal_value": "₹50,000/mo",
        "avg_ticket_inr": "₹15–50K/mo retainers",
        "pitch_hook": "white-label our voice agents — sell lead-gen calling to your clients under your brand",
        "lead_band": "B",  # voice-product band (ADR-009; old per-lead mid ₹1400)
        "qualification_questions": [
            "Are you accepting new white-label partners?",
            "What is your minimum retainer?",
            "Do you specialize in any specific industry?",
        ],
    },
    "ca_legal": {
        "name": "CA & Legal Services",
        "tier": "B",
        "category": "leadgen",
        "content_focus": ["offer posts", "lead forms"],
        "target_type": "b2b",
        "b2b_client": "CA firms, compliance/legal service providers",
        "end_customer": "SMBs/startups (GST, ROC, IP, compliance needs → consult booking)",
        "keywords": [
            "ca firms",
            "chartered accountants",
            "compliance services",
            "corporate law firms",
        ],
        "avg_deal_value": "₹50,000+",
        "avg_ticket_inr": "₹10–50K recurring engagements",
        "pitch_hook": "compliance-season pipelines filled — qualified SMBs booked while rivals rely on referrals",
        "lead_band": "B",  # voice-product band (ADR-009; old per-lead mid ₹1050)
        "qualification_questions": [
            "Which services do you focus on — GST, ROC, audit, IP?",
            "Do you serve startups/SMBs?",
            "What is your typical engagement value?",
        ],
    },
    # ====================================================================== #
    # MARKETING NICHES — local-business categories jinhe hum AI-marketing
    # (posts / GBP / posters / festivals / reviews / reels) bechte hain.
    # category="marketing"; monthly_starter ₹2,999 retainer; pricing modest.
    # ====================================================================== #
    "restaurant_cafe": {
        "name": "Restaurant / Cafe",
        "tier": "S",
        "category": "marketing",
        "content_focus": ["reels", "menu posters", "reviews", "festival posters"],
        "target_type": "b2c",
        "b2b_client": "Restaurants, cafes, cloud kitchens, food joints",
        "end_customer": "Local foodies & families (footfall + online orders)",
        "keywords": ["restaurant", "cafe", "cloud kitchen", "food joint", "dhaba"],
        "avg_deal_value": "₹35,988/yr",
        "avg_ticket_inr": "₹2,999/mo retainer (₹36K/yr LTV)",
        "pitch_hook": "roz ki dish reels, menu posters aur festival offers — Insta+Google pe aapka restaurant chamke, footfall badhe",
        "lead_band": "A",  # voice-product band (ADR-009; old per-lead mid ₹200)
        "qualification_questions": [
            "Abhi aap restaurant ki marketing kaise karte ho — khud post karte ho ya koi karta hai?",
            "Instagram aur Google pe roz naye photos/reels daalte ho kya?",
            "Festival ya naye offer ke posters kaun banata hai?",
        ],
    },
    "automobile_service": {
        "name": "Automobile / Car Service",
        "tier": "B",
        "category": "marketing",
        "content_focus": ["service-offer posters", "festival posters", "reviews"],
        "target_type": "b2c",
        "b2b_client": "Car/bike service centers, garages, detailing studios",
        "end_customer": "Local vehicle owners (service bookings + walk-ins)",
        "keywords": ["car service", "garage", "auto repair", "bike service", "car detailing"],
        "avg_deal_value": "₹35,988/yr",
        "avg_ticket_inr": "₹2,999/mo retainer (₹36K/yr LTV)",
        "pitch_hook": "service-offer aur seasonal-check posters — Google pe rank karke nazdeeki gaadi-walon ko laaye",
        "lead_band": "A",  # voice-product band (ADR-009; old per-lead mid ₹200)
        "qualification_questions": [
            "Abhi service center ki marketing kaise karte ho?",
            "Google pe aapka garage search karne par dikhta hai kya?",
            "Service offer ke posters kaun banata hai?",
        ],
    },
    "photography_studio": {
        "name": "Photography / Wedding Studio",
        "tier": "B",
        "category": "marketing",
        "content_focus": ["portfolio reels", "festival posters", "reviews"],
        "target_type": "b2c",
        "b2b_client": "Photography & wedding studios, photographers",
        "end_customer": "Couples & families (shoots, wedding bookings)",
        "keywords": [
            "photography studio",
            "wedding photographer",
            "photo studio",
            "candid photography",
        ],
        "avg_deal_value": "₹35,988/yr",
        "avg_ticket_inr": "₹2,999/mo retainer (₹36K/yr LTV)",
        "pitch_hook": "aapke best shoots ke portfolio reels — Insta pe dikhe to wedding aur event bookings khud aayein",
        "lead_band": "A",  # voice-product band (ADR-009; old per-lead mid ₹275)
        "qualification_questions": [
            "Abhi studio ki marketing kaise hoti hai — khud Insta chalate ho?",
            "Apne best shoots ke reels banate ho kya?",
            "Wedding season ke offer posters kaun banata hai?",
        ],
    },
    "pharmacy_medical": {
        "name": "Pharmacy / Medical Store",
        "tier": "B",
        "category": "marketing",
        "content_focus": ["GBP optimization", "health-day posts", "offers"],
        "target_type": "b2c",
        "b2b_client": "Pharmacies, medical & chemist stores",
        "end_customer": "Local customers (footfall + home-delivery orders)",
        "keywords": ["pharmacy", "medical store", "chemist", "medical shop", "drug store"],
        "avg_deal_value": "₹35,988/yr",
        "avg_ticket_inr": "₹2,999/mo retainer (₹36K/yr LTV)",
        "pitch_hook": "Google Business Profile + health-day posts — nazdeeki log aapki dukaan dhoondh ke pahunchein aur delivery maangein",
        "lead_band": "A",  # voice-product band (ADR-009; old per-lead mid ₹200)
        "qualification_questions": [
            "Google pe aapka medical store search karne par dikhta hai kya?",
            "Home delivery offer karte ho — log ko pata hai kya?",
            "Abhi koi WhatsApp/Insta pe marketing karta hai?",
        ],
    },
    "furniture_decor": {
        "name": "Furniture / Home Decor",
        "tier": "B",
        "category": "marketing",
        "content_focus": ["catalog posters", "offers", "reels", "festival posters"],
        "target_type": "b2c",
        "b2b_client": "Furniture showrooms, home decor & furnishing stores",
        "end_customer": "Homeowners (showroom footfall + enquiries)",
        "keywords": [
            "furniture store",
            "home decor",
            "furnishing shop",
            "sofa shop",
            "furniture showroom",
        ],
        "avg_deal_value": "₹35,988/yr",
        "avg_ticket_inr": "₹2,999/mo retainer (₹36K/yr LTV)",
        "pitch_hook": "product catalog posters aur festival offers — naye design Insta+WhatsApp pe dikhein, footfall badhe",
        "lead_band": "A",  # voice-product band (ADR-009; old per-lead mid ₹200)
        "qualification_questions": [
            "Abhi furniture showroom ki marketing kaise karte ho?",
            "Naye products ke photos/catalog Insta pe daalte ho kya?",
            "Festival offer ke posters kaun banata hai?",
        ],
    },
    "kirana_supermarket": {
        "name": "Kirana / Supermarket",
        "tier": "B",
        "category": "marketing",
        "content_focus": ["WhatsApp offers", "festival posts", "offer posters"],
        "target_type": "b2c",
        "b2b_client": "Kirana stores, supermarkets, grocery shops",
        "end_customer": "Local households (repeat footfall + WhatsApp orders)",
        "keywords": [
            "kirana store",
            "supermarket",
            "grocery shop",
            "general store",
            "provision store",
        ],
        "avg_deal_value": "₹35,988/yr",
        "avg_ticket_inr": "₹2,999/mo retainer (₹36K/yr LTV)",
        "pitch_hook": "weekly WhatsApp offers aur festival posters — mohalle ke customers baar-baar aapki dukaan pe aayein",
        "lead_band": "A",  # voice-product band (ADR-009; old per-lead mid ₹165)
        "qualification_questions": [
            "Abhi customers ko offers kaise batate ho — WhatsApp pe ya nahi?",
            "Festival ya monthly offer ke posters kaun banata hai?",
            "Google pe aapki dukaan dikhti hai kya?",
        ],
    },
    "travel_agency": {
        "name": "Travel Agency / Tours",
        "tier": "B",
        "category": "marketing",
        "content_focus": ["package posters", "offers", "destination reels"],
        "target_type": "b2c",
        "b2b_client": "Travel agencies, tour & holiday operators",
        "end_customer": "Local travellers & families (package enquiries)",
        "keywords": [
            "travel agency",
            "tour operator",
            "holiday packages",
            "tour and travels",
            "ticketing agent",
        ],
        "avg_deal_value": "₹35,988/yr",
        "avg_ticket_inr": "₹2,999/mo retainer (₹36K/yr LTV)",
        "pitch_hook": "season package posters aur destination reels — Insta+WhatsApp pe travellers khud enquiry karein",
        "lead_band": "A",  # voice-product band (ADR-009; old per-lead mid ₹200)
        "qualification_questions": [
            "Abhi travel agency ki marketing kaise hoti hai?",
            "Package ya offer ke posters kaun banata hai?",
            "Instagram pe destinations ke reels/photos daalte ho kya?",
        ],
    },
    "gift_stationery": {
        "name": "Gift / Stationery Shop",
        "tier": "B",
        "category": "marketing",
        "content_focus": ["festival posters", "offer posters", "product posts"],
        "target_type": "b2c",
        "b2b_client": "Gift shops, stationery & novelty stores",
        "end_customer": "Local buyers (occasion + festival footfall)",
        "keywords": ["gift shop", "stationery shop", "gift store", "novelty store", "card shop"],
        "avg_deal_value": "₹35,988/yr",
        "avg_ticket_inr": "₹2,999/mo retainer (₹36K/yr LTV)",
        "pitch_hook": "Rakhi-Diwali-Valentine ke gift posters aur offers — har occasion pe customers aapki shop yaad rakhein",
        "lead_band": "A",  # voice-product band (ADR-009; old per-lead mid ₹165)
        "qualification_questions": [
            "Abhi gift/stationery shop ki marketing kaise karte ho?",
            "Festival aur occasion ke posters kaun banata hai?",
            "Instagram/WhatsApp pe naye gift items daalte ho kya?",
        ],
    },
    "hospital_appointments": {
        "name": "Hospitals & Clinics — Appointment Booking",
        "tier": "A",
        "category": "both",
        "content_focus": [
            "doctor intro reels",
            "health-awareness posts",
            "patient testimonials",
            "OPD timing posts",
            "health-camp announcements",
        ],
        "target_type": "b2c",
        "b2b_client": "Multispecialty hospitals, polyclinics & nursing homes",
        "end_customer": "Patients / families (symptom query → right doctor → OPD appointment booked; follow-up reminders)",
        "keywords": [
            "multispecialty hospital",
            "polyclinic",
            "nursing home",
            "general hospital",
            "super speciality hospital",
            "day care clinic",
        ],
        "avg_deal_value": "₹83,988/yr",
        "avg_ticket_inr": "₹6,999/mo retainer (₹84K/yr LTV)",
        "pitch_hook": "AI agent 24×7 inbound calls handle karta hai — symptom sunta hai, sahi doctor suggest karta hai, OPD appointment book karta hai, reminder bhejta hai; hospital staff free rehta hai",
        "lead_band": "A",  # voice-product band
        "qualification_questions": [
            "Hospital me roz kitne inbound inquiry calls aate hain aur kitne miss hote hain?",
            "Abhi appointment booking kaun handle karta hai — receptionist ya WhatsApp?",
            "Kaun-kaun se departments hain jahan patient zyada poochh-taach karte hain?",
        ],
        "niche_script": {
            "greeting": "Namaste! Main {hospital_name} ka AI assistant hoon. Aap kis department ya doctor se appointment lena chahte hain?",
            "qualification": [
                "Aapko kya takleef ho rahi hai — thoda bata sakte hain taaki main sahi doctor suggest kar sakoon?",
                "Appointment kab chahiye — aaj, kal, ya koi specific date?",
                "Aapka naam aur contact number bata dijiye, confirm karte hain.",
            ],
            "objection_handling": {
                "price": "Hamare saath sirf qualified appointments pe charge hota hai — missed calls ya no-shows pe nahi.",
                "trust": "Humara AI agent TRAI-compliant hai — aur sirf appointment book karta hai, medical advice nahi deta.",
                "already_have": "Receptionist saari calls handle nahi kar paate — raat ko, Sunday ko, ya rush hour me calls miss hoti hain. Wahi gap hum fill karte hain.",
            },
        },
    },
    "skin_dermatology": {
        "name": "Dermatology & Skin Clinics",
        "tier": "A",
        "category": "both",
        "content_focus": [
            "before-after reels",
            "skin-tip carousels",
            "doctor intro reels",
            "patient testimonials",
            "offer creatives",
        ],
        "target_type": "b2c",
        "b2b_client": "Dermatology clinics, skin & hair treatment centers, cosmetology clinics",
        "end_customer": "Urban patients 18–45 (acne, pigmentation, anti-aging, laser, PRP → consultation booking)",
        "keywords": [
            "dermatologist clinic",
            "skin clinic",
            "cosmetology clinic",
            "laser treatment clinic",
            "hair loss treatment",
        ],
        "avg_deal_value": "₹83,988/yr",
        "avg_ticket_inr": "₹6,999/mo retainer (₹84K/yr LTV)",
        "pitch_hook": "Instagram pe before-after reels aur skin-tip carousels — doctor influencer ban jaayein, mahine me 50+ naye consultation bookings",
        "lead_band": "A",
        "qualification_questions": [
            "Abhi clinic ki marketing kaise hoti hai — Insta posts khud daalte ho ya koi?",
            "Before-after photos ya patient testimonials post karte ho kya?",
            "Skin/hair treatment ke liye roz kitne inquiry calls aate hain?",
        ],
    },
    "finance_advisory": {
        "name": "Insurance & Mutual Fund Advisors",
        "tier": "A",
        "category": "both",
        "content_focus": [
            "financial literacy posts",
            "SIP/returns infographics",
            "insurance awareness reels",
            "tax-saving tips",
            "client success stories",
        ],
        "target_type": "b2c",
        "b2b_client": "LIC/POSP agents, mutual fund distributors, financial advisors, DSAs",
        "end_customer": "Salaried professionals & families (investment, insurance, tax planning → advisory call)",
        "keywords": [
            "financial advisor",
            "mutual fund distributor",
            "insurance agent",
            "lic agent",
            "investment advisor",
        ],
        "avg_deal_value": "₹59,988/yr",
        "avg_ticket_inr": "₹4,999/mo retainer (₹60K/yr LTV)",
        "pitch_hook": "SIP aur insurance content se trust banta hai — 81% log Meta pe finance product dhundhte hain; aapka AI agent 24×7 inquiry handle kare",
        "lead_band": "B",
        "qualification_questions": [
            "Abhi advisory business ki marketing kaise karte ho — referral pe depend ho?",
            "Financial literacy posts ya SIP infographics daalte ho Insta/Facebook pe?",
            "Roz kitne naye clients ki zaroorat hai growth ke liye?",
        ],
    },
    "edtech_creators": {
        "name": "Online Educators & Course Creators",
        "tier": "A",
        "category": "marketing",
        "content_focus": [
            "knowledge reels",
            "student result posts",
            "course promo creatives",
            "free-value carousels",
            "testimonial videos",
        ],
        "target_type": "b2c",
        "b2b_client": "Independent educators, YouTubers, online course sellers, skill trainers",
        "end_customer": "Students & working professionals (free content → paid course → community)",
        "keywords": [
            "online course creator",
            "youtube educator",
            "digital educator",
            "skill trainer online",
            "certification course online",
        ],
        "avg_deal_value": "₹59,988/yr",
        "avg_ticket_inr": "₹4,999/mo retainer (₹60K/yr LTV)",
        "pitch_hook": "roz ek reel, ek carousel — audience badhao, course becho; AI content engine jo aapki voice me likhta hai",
        "lead_band": "A",
        "qualification_questions": [
            "Abhi social media pe content kitni baar post karte ho?",
            "Paid course ya community bechte ho?",
            "Kaun-si platform pe sabse zyada audience hai — YouTube, Insta ya LinkedIn?",
        ],
    },
    "cloud_kitchen": {
        "name": "Cloud Kitchen / Tiffin Service",
        "tier": "A",
        "category": "marketing",
        "content_focus": [
            "food reels",
            "menu posts",
            "customer review posts",
            "offer creatives",
            "behind-the-scenes reels",
        ],
        "target_type": "b2c",
        "b2b_client": "Cloud kitchens, tiffin services, home chefs, dark kitchens",
        "end_customer": "Urban working professionals & families (Zomato/Swiggy + direct WhatsApp orders)",
        "keywords": [
            "cloud kitchen",
            "tiffin service",
            "home food delivery",
            "dark kitchen",
            "meal subscription",
        ],
        "avg_deal_value": "₹35,988/yr",
        "avg_ticket_inr": "₹2,999/mo retainer (₹36K/yr LTV)",
        "pitch_hook": "food reels aur daily menu posts — Insta+WhatsApp se direct orders badhao, Zomato commission bachao",
        "lead_band": "A",
        "qualification_questions": [
            "Abhi orders kahan se aate hain — Zomato/Swiggy ya direct WhatsApp?",
            "Food photos ya reels regularly daalte ho social media pe?",
            "Monthly kitne orders chahiye business stable karne ke liye?",
        ],
    },
    "ayurveda_wellness": {
        "name": "Ayurveda & Wellness Clinics",
        "tier": "B",
        "category": "both",
        "content_focus": [
            "health-tip reels",
            "treatment awareness posts",
            "doctor intro carousels",
            "patient testimonials",
            "seasonal wellness posts",
        ],
        "target_type": "b2c",
        "b2b_client": "Ayurveda clinics, panchakarma centers, naturopathy & holistic wellness centers",
        "end_customer": "Health-conscious urban & semi-urban patients (chronic issues, immunity, weight → consultation)",
        "keywords": [
            "ayurveda clinic",
            "panchakarma center",
            "naturopathy clinic",
            "holistic wellness",
            "ayurvedic doctor",
        ],
        "avg_deal_value": "₹59,988/yr",
        "avg_ticket_inr": "₹4,999/mo retainer (₹60K/yr LTV)",
        "pitch_hook": "seasonal health tips aur treatment awareness reels — India-specific content jo log genuinely share karte hain",
        "lead_band": "A",
        "qualification_questions": [
            "Abhi clinic ki marketing kaise hoti hai?",
            "Seasonal health posts ya Ayurvedic tips social media pe daalte ho?",
            "Roz kitne naye consultation bookings chahiye?",
        ],
    },
    "ecommerce_d2c": {
        "name": "D2C / E-commerce Brand Owners",
        "tier": "A",
        "category": "marketing",
        "content_focus": [
            "product reels",
            "unboxing videos",
            "offer & sale creatives",
            "UGC-style posts",
            "festival sale banners",
        ],
        "target_type": "b2c",
        "b2b_client": "D2C brands, Shopify/WooCommerce store owners, Amazon/Flipkart sellers going direct",
        "end_customer": "Online shoppers (product discovery → add-to-cart via Instagram/WhatsApp)",
        "keywords": [
            "d2c brand india",
            "ecommerce store india",
            "shopify store india",
            "online seller",
            "direct to consumer brand",
        ],
        "avg_deal_value": "₹71,988/yr",
        "avg_ticket_inr": "₹5,999/mo retainer (₹72K/yr LTV)",
        "pitch_hook": "roz product reels aur festival sale banners — Instagram pe brand dikhao, website pe traffic laao, Amazon pe rank karo",
        "lead_band": "A",
        "qualification_questions": [
            "Abhi store ka social media kaun handle karta hai?",
            "Product photos aur reels regularly post karte ho?",
            "Festival sale pe (Diwali/Republic Day) extra budget hota hai marketing ka?",
        ],
    },
    "event_management": {
        "name": "Corporate & Social Event Planners",
        "tier": "B",
        "category": "both",
        "content_focus": [
            "event highlight reels",
            "behind-the-scenes videos",
            "portfolio posts",
            "testimonial creatives",
            "theme inspiration carousels",
        ],
        "target_type": "both",
        "b2b_client": "Event management companies, wedding planners, corporate event agencies",
        "end_customer": "Corporates (offsites, product launches) + families (birthdays, anniversaries, themed parties)",
        "keywords": [
            "event management company",
            "corporate event planner",
            "event organizer",
            "birthday party organizer",
            "wedding planner",
        ],
        "avg_deal_value": "₹59,988/yr",
        "avg_ticket_inr": "₹4,999/mo retainer (₹60K/yr LTV)",
        "pitch_hook": "event highlight reels aur portfolio posts — Insta pe dikhoge to corporates aur families khud enquiry karein",
        "lead_band": "A",
        "qualification_questions": [
            "Corporate events aur social events dono karte ho?",
            "Past events ke photos/reels social media pe daalte ho?",
            "Roz kitne naye event inquiries chahiye?",
        ],
    },
    "hardware_paint": {
        "name": "Hardware / Paint / Electrical",
        "tier": "B",
        "category": "marketing",
        "content_focus": ["offer posters", "festival posters", "product posts"],
        "target_type": "b2c",
        "b2b_client": "Hardware, paint & electrical supply shops",
        "end_customer": "Homeowners, contractors & local trade (footfall + enquiries)",
        "keywords": [
            "hardware shop",
            "paint shop",
            "electrical store",
            "sanitary shop",
            "building material",
        ],
        "avg_deal_value": "₹35,988/yr",
        "avg_ticket_inr": "₹2,999/mo retainer (₹36K/yr LTV)",
        "pitch_hook": "offer aur festival posters + Google listing — contractors aur ghar-walon ko aapki dukaan aasani se mile",
        "lead_band": "A",  # voice-product band (ADR-009; old per-lead mid ₹200)
        "qualification_questions": [
            "Abhi hardware/paint shop ki marketing kaise hoti hai?",
            "Google pe aapki dukaan search karne par dikhti hai kya?",
            "Offer ya naye product ke posters kaun banata hai?",
        ],
    },
    "tiffin_service": {
        "name": "Tiffin / Home Food Service",
        "tier": "B",
        "category": "marketing",
        "content_focus": [
            "menu posters",
            "weekly offers",
            "WhatsApp order flow",
            "testimonial posts",
        ],
        "target_type": "b2c",
        "b2b_client": "Tiffin services, home-food kitchens, office bulk lunch suppliers",
        "end_customer": "Working professionals & families (monthly subscriptions, office zones)",
        "keywords": [
            "tiffin service",
            "home food",
            "tiffin near me",
            "office lunch",
            "monthly tiffin",
        ],
        "avg_deal_value": "₹35,988/yr",
        "avg_ticket_inr": "₹2,999/mo retainer (₹36K/yr LTV)",
        "pitch_hook": "roz ke menu posters aur monthly-subscription offers — office zones aur mohalle ke log aapka tiffin order karein",
        "lead_band": "A",  # voice-product band (ADR-009; mass-local)
        "qualification_questions": [
            "Abhi tiffin orders kaise milte hain — WhatsApp pe ya word-of-mouth?",
            "Monthly subscription plan hai kya, ya sirf ek-din ke orders?",
            "Menu photos/offers ke posters kaun banata hai?",
        ],
    },
    "gents_salon": {
        "name": "Men's Salon / Barber",
        "tier": "B",
        "category": "marketing",
        "content_focus": ["before-after reels", "styling posts", "offer posters", "reviews"],
        "target_type": "b2c",
        "b2b_client": "Men's salons, barbershops, grooming studios",
        "end_customer": "Men (walk-ins + appointments)",
        "keywords": ["men's salon", "barber shop", "salon near me", "haircut", "grooming studio"],
        "avg_deal_value": "₹35,988/yr",
        "avg_ticket_inr": "₹2,999/mo retainer (₹36K/yr LTV)",
        "pitch_hook": "before-after reels aur beard/haircut styling posts — Insta+Google pe nazdeeki clients ko apni kala dikhayein, bookings aayein",
        "lead_band": "A",  # voice-product band (ADR-009; mass-local)
        "qualification_questions": [
            "Abhi salon ki marketing kaise hoti hai — khud Insta chalate ho?",
            "Before-after photos/reels banate ho kya?",
            "Google reviews collect karte ho kya — 'salon near me' pe dikhte ho?",
        ],
    },
    "tuition_classes": {
        "name": "Tuition Classes",
        "tier": "B",
        "category": "marketing",
        "content_focus": ["result posts", "admission offers", "faculty reels", "reviews"],
        "target_type": "b2c",
        "b2b_client": "Coaching/tuition classes, home tutors, test-prep centres",
        "end_customer": "Students & parents (admissions, batch enrollments)",
        "keywords": [
            "tuition classes",
            "coaching near me",
            "tuition near me",
            "home tuition",
            "test prep",
        ],
        "avg_deal_value": "₹35,988/yr",
        "avg_ticket_inr": "₹2,999/mo retainer (₹36K/yr LTV)",
        "pitch_hook": "student result posts aur admission offers — parents ko bharosa dilayein, naye admission aayein",
        "lead_band": "A",  # voice-product band (ADR-009; mass-local)
        "qualification_questions": [
            "Abhi naye admissions kaise aate hain — word-of-mouth ya ads?",
            "Students ke results/toppers ke posts karte ho kya?",
            "Admission season me koi offer chalta hai kya?",
        ],
    },
    "play_school": {
        "name": "Play School / Preschool",
        "tier": "B",
        "category": "marketing",
        "content_focus": [
            "campus photos",
            "activities reels",
            "parent reviews",
            "admission offers",
        ],
        "target_type": "b2c",
        "b2b_client": "Play schools, preschools, daycare centres",
        "end_customer": "Parents of 2-6 year olds (admissions)",
        "keywords": [
            "play school",
            "preschool near me",
            "daycare",
            "nursery school",
            "playschool admission",
        ],
        "avg_deal_value": "₹35,988/yr",
        "avg_ticket_inr": "₹2,999/mo retainer (₹36K/yr LTV)",
        "pitch_hook": "campus photos aur activities reels — parents ko safe learning space dikhayein, admission season me inquiries aayein",
        "lead_band": "A",  # voice-product band (ADR-009; mass-local)
        "qualification_questions": [
            "Abhi admissions kaise aate hain — referrals ya ads?",
            "Campus photos/activities ke posts karte ho kya?",
            "Parent reviews kaise collect karte ho?",
        ],
    },
    "laundry_dryclean": {
        "name": "Laundry / Dry-Clean Service",
        "tier": "B",
        "category": "marketing",
        "content_focus": [
            "home-pickup offers",
            "festival dry-clean offers",
            "review posts",
            "service menu posters",
        ],
        "target_type": "b2c",
        "b2b_client": "Laundries, dry-cleaners, wash-and-fold services",
        "end_customer": "Local households & working professionals (pickup + walk-in)",
        "keywords": [
            "laundry",
            "dry cleaning near me",
            "laundry near me",
            "wash and fold",
            "dryclean",
        ],
        "avg_deal_value": "₹35,988/yr",
        "avg_ticket_inr": "₹2,999/mo retainer (₹36K/yr LTV)",
        "pitch_hook": "home-pickup aur festival dry-clean offers — societies aur office zones ke log aapki laundry ko repeat order karein",
        "lead_band": "A",  # voice-product band (ADR-009; mass-local)
        "qualification_questions": [
            "Abhi laundry ke naye customers kaise aate hain — word-of-mouth ya ads?",
            "Home pickup/delivery dete hain kya, kaunse zones me?",
            "Google pe 'laundry near me' pe dikhte hain kya — reviews?",
        ],
    },
    "electronics_repair": {
        "name": "Mobile / Electronics Repair",
        "tier": "B",
        "category": "marketing",
        "content_focus": [
            "repair offer posters",
            "doorstep service posts",
            "before-after fix reels",
            "reviews",
        ],
        "target_type": "b2c",
        "b2b_client": "Mobile repair shops, electronics & appliance service centres",
        "end_customer": "Local customers (walk-in repairs + doorstep service)",
        "keywords": [
            "mobile repair",
            "mobile repair near me",
            "phone repair",
            "laptop repair",
            "electronics repair",
        ],
        "avg_deal_value": "₹35,988/yr",
        "avg_ticket_inr": "₹2,999/mo retainer (₹36K/yr LTV)",
        "pitch_hook": "doorstep repair aur warranty offers — 'mobile repair near me' pe dikho to naye customers aate hain",
        "lead_band": "A",  # voice-product band (ADR-009; mass-local)
        "qualification_questions": [
            "Abhi repair business ke naye customers kaise aate hain?",
            "Doorstep service dete hain kya aur warranty?",
            "Google pe 'mobile repair near me' pe dikhte hain kya — reviews?",
        ],
    },
    "real_estate_luxury": {
        "name": "Real Estate (Premium / Luxury)",
        "tier": "B",
        "category": "both",
        "content_focus": [
            "luxury project launches",
            "sea-view / gated residence posts",
            "NRI virtual tour reels",
            "private site-visit offers",
        ],
        "target_type": "b2c",
        "b2b_client": "Premium real estate developers, luxury brokers & HNI-focused agencies (₹2cr+)",
        "end_customer": "High-net-worth home buyers/investors — privacy, NRI remote buying, curated inventory",
        "keywords": [
            "luxury flats",
            "sea view apartment",
            "2 crore property",
            "premium project launch",
            "NRI property",
        ],
        "avg_deal_value": "₹2,00,00,000+",
        "avg_ticket_inr": "₹19,999/mo voice (band C premium)",
        "pitch_hook": "₹2cr+ luxury property leads — private site visits + NRI virtual tours, inventory sirf serious buyers ko",
        "lead_band": "C",  # voice-product band (ADR-009; premium-HNI)
        "qualification_questions": [
            "Premium segment me kaunse areas/locations aapka main market hain?",
            "NRI ya HNI buyers ke liye alag process hai kya — virtual tours?",
            "Confidentiality aur exclusive inventory ke liye kaise handle karte ho?",
        ],
    },
    "salon_spa": {
        "name": "Salons & Beauty Parlours",
        "tier": "B",
        "category": "marketing",
        "content_focus": [
            "before-after reels",
            "bridal package offers",
            "offer posters",
            "review posts",
        ],
        "target_type": "b2c",
        "b2b_client": "Salons, beauty parlours, unisex & bridal studios",
        "end_customer": "Local customers (walk-ins + appointments, bridal bookings)",
        "keywords": [
            "salon near me",
            "beauty parlour near me",
            "bridal makeup",
            "facial",
            "hair spa",
        ],
        "avg_deal_value": "₹35,988/yr",
        "avg_ticket_inr": "₹2,999/mo retainer (₹36K/yr LTV)",
        "pitch_hook": "bridal packages + before-after reels — 'salon near me' pe rank karo to repeat bookings aate hain",
        "lead_band": "A",  # voice-product band (ADR-009; mass-local)
        "qualification_questions": [
            "Abhi salon ke naye customers kaise aate hain — walk-ins ya ads?",
            "Bridal packages/offers chalate ho kya?",
            "Google pe 'salon near me' pe dikhte ho kya — reviews?",
        ],
    },
    "gym_fitness": {
        "name": "Gyms & Fitness Studios",
        "tier": "B",
        "category": "marketing",
        "content_focus": [
            "transformation reels",
            "joining offer posters",
            "membership posts",
            "review reels",
        ],
        "target_type": "b2c",
        "b2b_client": "Gyms, fitness studios, crossfit boxes, yoga centres",
        "end_customer": "Local members (Jan rush, summer prep, PT seekers)",
        "keywords": [
            "gym near me",
            "fitness studio",
            "gym membership",
            "personal trainer",
            "yoga classes near me",
        ],
        "avg_deal_value": "₹35,988/yr",
        "avg_ticket_inr": "₹2,999/mo retainer (₹36K/yr LTV)",
        "pitch_hook": "transformation reels + joining offers — 'gym near me' pe dikho to January/summer rush miss nahi hota",
        "lead_band": "A",  # voice-product band (ADR-009; mass-local)
        "qualification_questions": [
            "Abhi gym ke naye members kaise aate hain — referrals ya ads?",
            "Seasonal offers (January/summer) chalate ho kya?",
            "Google pe 'gym near me' pe dikhte ho kya — reviews?",
        ],
    },
    "boutique_fashion": {
        "name": "Boutique & Fashion Stores",
        "tier": "B",
        "category": "marketing",
        "content_focus": [
            "collection reels",
            "festive offer posters",
            "new-arrival posts",
            "customer reviews",
        ],
        "target_type": "b2c",
        "b2b_client": "Boutiques, fashion stores, designer studios",
        "end_customer": "Local shoppers (festive + wedding wear, repeat customers)",
        "keywords": [
            "boutique near me",
            "designer wear",
            "festive collection",
            "custom stitching",
            "bridal wear",
        ],
        "avg_deal_value": "₹35,988/yr",
        "avg_ticket_inr": "₹2,999/mo retainer (₹36K/yr LTV)",
        "pitch_hook": "naye collection + festive offers — repeat WhatsApp orders aur reviews se 'boutique near me' pe rank",
        "lead_band": "A",  # voice-product band (ADR-009; mass-local)
        "qualification_questions": [
            "Abhi boutique ke naye customers kaise aate hain — Instagram ya walk-ins?",
            "Festive/wedding season me special collections/offers rakhte ho kya?",
            "Google pe 'boutique near me' pe dikhte ho kya — reviews?",
        ],
    },
    "bakery_sweets": {
        "name": "Bakeries & Sweet Shops",
        "tier": "B",
        "category": "marketing",
        "content_focus": [
            "menu posters",
            "festive sweet offers",
            "cake order posts",
            "review posts",
        ],
        "target_type": "b2c",
        "b2b_client": "Bakeries, sweet shops, cake studios",
        "end_customer": "Local households & party orders (festive sweets, custom cakes)",
        "keywords": [
            "bakery near me",
            "cake shop near me",
            "sweet shop",
            "custom cake",
            "festive sweets",
        ],
        "avg_deal_value": "₹35,988/yr",
        "avg_ticket_inr": "₹2,999/mo retainer (₹36K/yr LTV)",
        "pitch_hook": "festive sweet/cake offers + WhatsApp order flow — party aur festive orders repeat hote hain",
        "lead_band": "A",  # voice-product band (ADR-009; mass-local)
        "qualification_questions": [
            "Abhi bakery ke naye customers kaise aate hain — walk-ins ya orders?",
            "Custom cakes ya festive sweet boxes lete hain kya?",
            "Google pe 'bakery near me' pe dikhte ho kya — reviews?",
        ],
    },
    "jewellery_store": {
        "name": "Jewellery Stores",
        "tier": "B",
        "category": "marketing",
        "content_focus": [
            "collection reels",
            "festive offer posters",
            "gold-scheme posts",
            "customer reviews",
        ],
        "target_type": "b2c",
        "b2b_client": "Jewellery stores, gold/silver shops, designer jewellers",
        "end_customer": "Local shoppers (wedding + festive jewellery, gold schemes)",
        "keywords": [
            "jewellery shop near me",
            "gold rate today",
            "bridal jewellery",
            "gold scheme",
            "silver jewellery",
        ],
        "avg_deal_value": "₹59,988/yr",
        "avg_ticket_inr": "₹4,999/mo retainer (₹60K/yr LTV)",
        "pitch_hook": "festive collection + gold-scheme offers — wedding season aur festive pe walk-ins double hote hain",
        "lead_band": "B",  # voice-product band (ADR-009; higher-ticket retail)
        "qualification_questions": [
            "Abhi jewellery store ke naye customers kaise aate hain — walk-ins ya referrals?",
            "Gold schemes ya festive offers chalate ho kya?",
            "Google pe 'jewellery shop near me' pe dikhte ho kya — reviews?",
        ],
    },
}
