#!/usr/bin/env python3
"""Regenerate the KNOWN_UNRESOLVED_DEBT baseline (LOCAL ONLY).

This is deliberately a separate script and is NOT wired into CI. Updating the
baseline is a governed action: a developer runs this, reads the diff, and
commits the exact change with a reason. If CI could regenerate it, the ratchet
would silently absorb every new writer -- which is the same thing as having no
ratchet, dressed up as automation.

There is no `--accept-current-state` here or anywhere else. This script rebuilds
the inventory from the scanner; it does not decide that anything is safe.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.platform import runtime_data_allowlist as _allow  # noqa: E402
from app.platform import runtime_data_ratchet as _ratchet  # noqa: E402
from app.platform import runtime_data_scan as _scan  # noqa: E402

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "app" / "platform" / "runtime_data_baseline.py"

HEADER = '''"""KNOWN_UNRESOLVED_DEBT — frozen inventory of unclassified mutable paths.

GENERATED by scripts/runtime_data_baseline_gen.py. Do not hand-edit; regenerate
and review the diff.

These entries are NOT approvals. Each one means only: "this finding existed when
the inventory was frozen, and CI tolerates it until someone classifies it."
Nothing here has an owner, a migration wave or a store authority, because none
of that has been established -- inventing it would be fabricated evidence.

An entry leaves this file by being CLASSIFIED (allowlist entry with real
evidence, or migration behind app/platform/runtime_data.py), never by being
re-approved.

review_state values:
  AMBIGUOUS_PENDING_CLASSIFICATION — read/import-time reference, authority unknown
  UNDECLARED_PENDING_CLASSIFICATION — mutating writer, store not yet established
"""

from __future__ import annotations

from typing import Any

SCANNER_VERSION = {scanner_version!r}
FIRST_RECORDED_HEAD = {head!r}
FIRST_RECORDED_BRANCH = {branch!r}

ENTRIES: list[dict[str, Any]] = [
'''

FOOTER = """]

__all__ = ["SCANNER_VERSION", "FIRST_RECORDED_HEAD", "FIRST_RECORDED_BRANCH", "ENTRIES"]
"""


def _git(*args: str) -> str:
    try:
        return subprocess.run(  # noqa: S603
            ["git", *args], cwd=str(REPO), capture_output=True, text=True, timeout=30
        ).stdout.strip()
    except Exception:
        return "unknown"


def main() -> int:
    findings = _scan.scan_repo(REPO, allowlist=_allow.load())
    unresolved = [f for f in findings if f["classification"] in _ratchet.UNRESOLVED]

    head = _git("rev-parse", "--short", "HEAD")
    branch = _git("rev-parse", "--abbrev-ref", "HEAD")

    rows: list[str] = []
    seen: set[str] = set()
    for f in sorted(unresolved, key=lambda x: (x["file"], x["line"], x["operation"])):
        fp = _scan.fingerprint(f)
        if fp in seen:
            # Same file+symbol+operation+path+classification on two lines is one
            # logical debt item, not two.
            continue
        seen.add(fp)
        state = (
            "AMBIGUOUS_PENDING_CLASSIFICATION"
            if f["classification"] == _scan.AMBIGUOUS_REQUIRES_REVIEW
            else "UNDECLARED_PENDING_CLASSIFICATION"
        )
        rows.append(
            "    {\n"
            f"        'finding_fingerprint': {fp!r},\n"
            f"        'identity': {_ratchet._identity(f)!r},\n"
            f"        'file': {f['file']!r},\n"
            f"        'symbol': {f.get('symbol')!r},\n"
            f"        'operation': {f['operation']!r},\n"
            f"        'normalized_path': {_scan.normalized_path(f)!r},\n"
            f"        'classification': {f['classification']!r},\n"
            f"        'store_id': {f.get('store_id')!r},\n"
            f"        'line_hint': {f['line']!r},\n"
            f"        'review_state': {state!r},\n"
            f"        'evidence': 'frozen at baseline; authority NOT established',\n"
            "    },"
        )

    body = HEADER.format(
        scanner_version=_scan.__name__ + "@" + head,
        head=head,
        branch=branch,
    )
    OUT.write_text(body + "\n".join(rows) + "\n" + FOOTER, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} with {len(rows)} unresolved entries")
    print("REVIEW THE DIFF before committing. These are debt records, not approvals.")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
